mtvSession/bookmark/urls.py
from django.urls import path

from bookmark.views import BookmarkLV,BookmarkDV

app_name = 'bookmark'
urlpatterns = [
    #class-based views
    path('',BookmarkLV.as_view(), name='index'),
    path('<int:pk>',BookmarkDV.as_view(), name='detail')   
]

mtvSession/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

import blog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name = "home"),
    path('blog/<int:blog_id>', blog.views.detail, name = "detail"),
    
    path('bookmark/', include('bookmark.urls'))
    # #class-based views
    # path('bookmark/',BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>',BookmarkDV.as_view(), name='detailpage')   
]

mtvSession/blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

mtvSession/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model) :
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self) :
        return self.title

mtvSession/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.

def home(request):
    blogs = Blog.objects
    return render(request, 'home.html', {'blogs': blogs})

def detail(request, blog_id):
    blog_detail = get_object_or_404(Blog, pk= blog_id)
    return render(request, 'detail.html', {'blog': blog_detail})

mtvSession/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.
class BookmarkLV(ListView) :
    model = Bookmark

class BookmarkDV(DetailView) :
    model = Bookmark

mtvSession/blog/templates/detail.html
<h1>detail page 입니다.</h1>

<div class="container">
    <h1>{{ blog.title }}</h1>
    <p>{{ blog.pub_date }}</p>
    <p>{{ blog.body }}</p>
    <a href="{% url 'home' %}">돌아가기</a>
</div>

mtvSession/blog/templates/home.html
<h1>homepage 입니닿ㅎㅎㅎ</h1>

<!-- {{blogs}} -->
<!-- {{blogs.all}} -->

{% for blog in blogs.all %}
    <div class="container">
        <h1>{{ blog.title }}</h1>
        <p>{{ blog.pub_date }}</p>
        <!-- <p>{{ blog.body }} </p> -->
        <p>{{ blog.summary }}<a href="{% url 'detail' blog.id %}">....more</a></p>
    </div>
{% endfor %}

mtvSession/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark Detail</title>
</head>
<body>
    <div id="content">
        <h1>{{ object.title }}</h1>

        <ul>
            <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
    </div>
</body>
</html>

mtvSession/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>